import torch

# 1. Load the original BEiT-3 checkpoint (contains all encoder weights)
# This model has the 64k embedding layer
orig = torch.load('./beit3_large_indomain_patch16_224.pth', map_location='cpu')
model_weights = orig['model']

# 2. Load your new XLMR-aligned embedding tensor
# This is the file generated by your 5 scripts (250k tokens)
new_embed = torch.load('./xlmr_in_beit3_space.pt', map_location='cpu')

# Logic to handle if the .pt file is a raw Tensor or a Dictionary
if isinstance(new_embed, dict):
    # Try to find the specific key or take the first available tensor
    embed_tensor = new_embed.get('beit3.text_embed.weight', next(iter(new_embed.values())))
else:
    embed_tensor = new_embed

print(f"Surgery in progress: replacing old shape {model_weights['beit3.text_embed.weight'].shape} with new shape {embed_tensor.shape}")

# 3. Surgical replacement of the embedding weight
model_weights['beit3.text_embed.weight'] = embed_tensor

# 4. Save the complete checkpoint in a format BEiT-3 expects (Dict with 'model' key)
torch.save({'model': model_weights}, './beit3_xlmr_final_ready.pt')
print("Success! Final checkpoint saved as: ./beit3_xlmr_final.pt")
